runtime: python310
entrypoint: gunicorn -b :$PORT api:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  MODEL_NAME: "ml6team/keyphrase-extraction-kbir-inspec"
  MODEL_DIRECTORY: "model"

runtime_config:
  python_version: 3.10